spring:
  datasource:
    url: jdbc:mysql://121.42.138.220:3306/jp_restaurant?useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true&characterEncoding=UTF-8
    username: jprestaurantprod
    password: jprestaurantprod
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      max-active: 49
      test-while-idle: true
      time-between-eviction-runs-millis: 599999
      validation-query: SELECT 1 FROM DUAL
      filters: config,wall,stat
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: false
      filter:
        wall:
          config:
            multi-statement-allow: true
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: /druid/*,*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico
        session-stat-enable: true
        session-stat-max-count: 9
      #StatViewServlet配置，说明请参考Druid Wiki，配置_StatViewServlet配置
      #是否启用StatViewServlet默认值true
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        login-password: admin
        login-username: admin
  redis:
    database: 8
    host: 121.42.138.220
    port: 6377
    password: samredis888